language: objective-c
osx_image: xcode7.2
script:
  - xcodebuild test -project Brownout.xcodeproj -scheme BrownoutTests -destination 'platform=iOS Simulator,name=iPhone 6s' ONLY_ACTIVE_ARCH=NO
  - xcodebuild test -project Brownout.xcodeproj -scheme BrownoutUITests -destination 'platform=iOS Simulator,name=iPhone 6s' ONLY_ACTIVE_ARCH=NO
xcode_project: Brownout.xcodeproj
xcode_scheme: BrownoutTests
xcode_sdk: iphonesimulator
notifications:
  email:
    - yukio.murakami@gmail.com
  slack: bitz-co-jp:PfDiPezGCdA0lBULaYYkgfNr
