language: objective-c
osx_image: xcode7.2
script:
  - xcodebuild test -project Brownout.xcodeproj -target BrownoutTests -scheme BrownoutTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xcodebuild test -project Brownout.xcodeproj -target BrownoutUITests -scheme BrownoutUITests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
xcode_project: Brownout.xcodeproj
xcode_scheme: BrownoutTests
xcode_sdk: iphonesimulator
notifications:
  email:
    - yukio.murakami@gmail.com
  slack: bitz-co-jp:PfDiPezGCdA0lBULaYYkgfNr
