language: objective-c
osx_image: xcode7.2
xcode_project: Brownout.xcodeproj
xcode_scheme: BrownoutTests
xcode_sdk: iphonesimulator
notifications:
  email: false
  slack: bitz-co-jp:PfDiPezGCdA0lBULaYYkgfNr
